name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose -p "ci-${{ github.run_id }}" build
