name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        id: build
        run: docker compose -p "ci-${{ github.run_id }}" build

      - name: Build status
        if: always()
        run: |
          if [ "${{ steps.build.outcome }}" = "success" ]; then
            echo "### BUILD SUCCESS" >> $GITHUB_STEP_SUMMARY
          else
            echo "### BUILD FAILED" >> $GITHUB_STEP_SUMMARY
          fi
